apiVersion: v2
name: cluster-essentials
version: "1.0"
dependencies:
- alias: searx 
  name: searxng
  version: "1.0"
  repository: "https://github.com/DrPepperMonkey/k8s-yamls/tree/40ac8a32d6d5f9e62049b8d08fd7ed576944721a/cluster-resources/helm-charts/searxng"
- alias: vault
  name: vault-warden
  version: "1.0"
  repository: "https://github.com/DrPepperMonkey/k8s-yamls/tree/40ac8a32d6d5f9e62049b8d08fd7ed576944721a/cluster-resources/helm-charts/vault-warden"
- alias: rss
  name: rss
  version: "1.0"
  repository: "https://github.com/DrPepperMonkey/k8s-yamls/tree/40ac8a32d6d5f9e62049b8d08fd7ed576944721a/cluster-resources/helm-charts/rss"
 - alias: adguard
  name: adguard-home
  version: "1.0"
  repository: "https://github.com/DrPepperMonkey/k8s-yamls/tree/f7cde09355e6e2f4206ceca29cc5af6b05b02fcf/cluster-resources/helm-charts/adguard"
- alias: plex
  name: plex
  version: "1.0"
  repository: "https://github.com/DrPepperMonkey/k8s-yamls/tree/40ac8a32d6d5f9e62049b8d08fd7ed576944721a/cluster-resources/helm-charts/plex"
