apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss-ingress
  namespace: rss
  annotations:
    rss.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: rss.dpmcentral.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rss-svc
            port:
              number: 80
