apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: call-dpmcentral-com-tls
  namespace: ess
spec:
  secretName: call-dpmcentral-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - call.dpmcentral.com
