apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitty # Name of the deployment
  namespace: arr # Name of the namespace
  labels:
    app: bitty # Name of your application
spec:
  selector:
    matchLabels:
      app: bitty # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: bitty # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: bitty # Name of the container
        image: lscr.io/linuxserver/qbittorrent:latest # The image you want to run
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.2"
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 8080 # The port that your application uses
          containerPort: 6881 # Torrenting port
