apiVersion: v1
kind: Service
metadata:
  name:  vpn-svc
  namespace: vpn
spec:
  selector:
    app:  vpn
  type:  ClusterIP
  ports:
  - name:  http
    port:  51820
    targetPort: 51820
    protocol: UDP
