apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-warden-ingress
  namespace: vault-warden
  annotations:
    vault-warden.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: vault.dpmcentral.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-warden-svc
            port:
              number: 80
