apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng # Name of the deployment
  namespace: searxng # Name of the namespace
  labels:
    app: searxng # Name of your application
spec:
  selector:
    matchLabels:
      app: searxng # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: searxng # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: searxng # Name of the container
        image: searxng/searxng:latest # The image you want to run
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.2"
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 8080 # The port that your application uses
        
---

apiVersion: v1
kind: Service
metadata:
  name:  searxng-svc
  namespace: searxng
spec:
  selector:
    app:  searxng
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort: 8080
