apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ssd1
spec:
  capacity:
    storage: 465Gb
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.50.170
    path: "/srv/nfs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ssd2
spec:
  capacity:
    storage: 931Gb
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.50.170
    path: "/srv/nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ssd1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 465Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ssd2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 931Mi
